files:
  web:
    loop: true
    src: audio/LOFI_LOOP_V0.wav
  call:
    loop: true
    src: audio/ENTREVISTA_V0.wav
  breath:
    loop: true
    src: audio/BreathFast.wav
  fire:
    loop: true
    src: audio/FUEGO.wav
  emailSound:
    loop: false
    src: audio/Email_Sound.wav
options:
  volume: 0.5
  musicFadeInTime: 0.5
  musicFadeInDelay: 0.5
  musicFadeOutTime: 0.5
audioTriggers: {}
