---
config:
  imagesPath: img/characters/
characters:
  game:
    name: ''
    color: white
  player:
    style:
      color: orange
    name: Tú
  entrevistadora:
    style:
      color: white
    name: Señora
