screens:
  default:
    background: img/backgrounds/default.png
  game:
    background: img/backgrounds/linkedin.png
  interview1:
    background: img/backgrounds/pavanormal.png
  interview2:
    background: img/backgrounds/pavaojeras.png
  interview3:
    background: img/backgrounds/pavasangre.png
  interview4:
    background: img/backgrounds/pavainfierno.png
  endInterview:
    background: img/backgrounds/pavamalacara.png
